"""Curses-based interactive viewer for a normalized session.

This is the default UX for ``copsearch view <id>`` when stdout is a TTY.
The screen is split into three regions:

    ┌──────────────────────────────────────┐
    │ session summary · model · cwd        │ ← top status bar (1 line)
    ├──────────────────────────────────────┤
    │                                      │
    │   ...rendered conversation...        │ ← scrollable body
    │                                      │
    ├──────────────────────────────────────┤
    │ j↓/k↑ scroll · n next · t tools · q  │ ← help bar (1 line, always visible)
    └──────────────────────────────────────┘

The body is generated by :func:`copsearch.render_cli.iter_lines` (plain
text, no ANSI). Color comes from a tiny per-line classifier — we look at
the leading characters of each line and assign a curses attribute pair.
This avoids parsing ANSI escape sequences while still giving the user a
clear visual distinction between roles, tool successes/failures, and
diffs.

Keybindings:

    j / ↓        line down
    k / ↑        line up
    space / Pg↓  half page down
    b / Pg↑      half page up
    g            top
    G            bottom
    n            jump to next user/assistant turn header
    N            jump to previous turn header
    t            cycle tools detail (brief → full → none)
    s            toggle system events (session start, skill, shutdown)
    /            search forward
    ?            search backward
    q / Esc      quit
"""

from __future__ import annotations

import copy
import curses
import locale
import re
from dataclasses import dataclass, field

from copsearch.normalize import NormalizedSession
from copsearch.render_cli import RenderOptions, iter_lines

HELP_BAR = (
    "j/↓ scroll · b/space page · g/G top/bot · n/N next-turn · "
    "t tools · s system · / ? search · q quit"
)

# ── Line classifiers ─────────────────────────────────────────────────────────
# Each pattern is checked top to bottom; the first match wins.
# Numbers correspond to curses color-pair indices initialised in ``_init_colors``.

PAIR_DEFAULT = 0
PAIR_USER = 1
PAIR_ASSISTANT = 2
PAIR_SYSTEM = 3
PAIR_TOOL_OK = 4
PAIR_TOOL_ERR = 5
PAIR_TOOL_WAIT = 6
PAIR_DIFF_ADD = 7
PAIR_DIFF_DEL = 8
PAIR_DIFF_HUNK = 9
PAIR_DIVIDER = 10
PAIR_HELP_BAR = 11
PAIR_TOP_BAR = 12
PAIR_DIM = 13
PAIR_HIGHLIGHT = 14

_RE_USER = re.compile(r"^▌ You")
_RE_ASSISTANT = re.compile(r"^▌ Assistant")
_RE_SYSTEM = re.compile(r"^[○◆]")
_RE_TOOL_OK = re.compile(r"^\s*(│\s*)*✓ ")
_RE_TOOL_ERR = re.compile(r"^\s*(│\s*)*✗ ")
_RE_TOOL_WAIT = re.compile(r"^\s*(│\s*)*⏳ ")
_RE_DIVIDER = re.compile(r"^[═─]+\s*$")
# In a result body these will be inside an indented context.
_RE_DIFF_ADD = re.compile(r"^\s{2,}\+(?!\+)")
_RE_DIFF_DEL = re.compile(r"^\s{2,}-(?!-)")
_RE_DIFF_HUNK = re.compile(r"^\s{2,}@@")
_RE_HEADER_LABEL = re.compile(r"^\s{2,}\S+:")  # "Session: ...", "Model: ..."
_RE_INDENT_DIM = re.compile(r"^\s{4,}")  # tool body indented content
_TURN_HEADER = re.compile(r"^▌ (You|Assistant)")


@dataclass
class _State:
    ns: NormalizedSession
    opts: RenderOptions
    lines: list[str] = field(default_factory=list)
    pairs: list[int] = field(default_factory=list)
    scroll: int = 0
    cursor_match: int = -1  # cursor index of the active search match, -1 if none
    tools_mode: str = "brief"
    show_system: bool = True
    search: str = ""
    last_search_dir: int = 1  # +1 forward, -1 backward
    message: str = ""

    def refresh_lines(self) -> None:
        """Re-render lines with current options. Recomputes color pairs too."""
        # Force plain-text generation; we apply colour ourselves via curses pairs.
        self.opts.color = False
        self.opts.tools = self.tools_mode
        self.opts.show_system_events = self.show_system
        self.lines = list(iter_lines(self.ns, self.opts))
        self.pairs = [_classify_line(ln) for ln in self.lines]

    def turn_starts(self) -> list[int]:
        return [i for i, ln in enumerate(self.lines) if _TURN_HEADER.match(ln)]


# ── Public entry point ──────────────────────────────────────────────────────


def view_in_curses(ns: NormalizedSession, opts: RenderOptions) -> int:
    """Run the interactive viewer. Returns the curses exit code (0 on success).

    Falls back to plain stdout printing if curses can't initialize (e.g. on
    a non-tty or in CI).

    The caller's ``opts`` is never mutated — we work on a private copy so
    that toggling tools/system inside the viewer doesn't bleed back into
    the surrounding CLI invocation.
    """
    # Some minimal/CI environments don't have a usable LC_ALL set; failing
    # here would skip the curses fallback below.
    try:
        locale.setlocale(locale.LC_ALL, "")
    except locale.Error:
        pass
    private_opts = copy.copy(opts)
    try:
        return curses.wrapper(_run, ns, private_opts) or 0
    except curses.error:
        # If curses couldn't init we render with the *caller's* opts so the
        # user gets whatever color/tool settings they asked for on the CLI.
        for line in iter_lines(ns, opts):
            print(line)
        return 0


# ── Main loop ────────────────────────────────────────────────────────────────


def _run(stdscr: curses._CursesWindow, ns: NormalizedSession, opts: RenderOptions) -> int:
    try:
        curses.curs_set(0)
    except curses.error:
        pass
    # ``use_default_colors`` and ``init_pair`` need colour support to be
    # initialised first. Some terminals (TERM=dumb, vt220, etc.) report no
    # colours at all — fall through to mono in that case.
    if curses.has_colors():
        try:
            curses.start_color()
            curses.use_default_colors()
            _init_colors()
        except curses.error:
            pass
    stdscr.timeout(-1)

    state = _State(ns=ns, opts=opts)
    # Honour what the user asked for on the CLI (--tools, --no-system).
    state.tools_mode = opts.tools
    state.show_system = opts.show_system_events
    state.refresh_lines()

    while True:
        _draw(stdscr, state)
        key = stdscr.get_wch() if hasattr(stdscr, "get_wch") else stdscr.getch()
        if _handle_key(state, stdscr, key) == "quit":
            return 0


def _init_colors() -> None:
    """Set up colour pairs. Uses default-bg by passing -1 as the second arg."""
    pairs = [
        (PAIR_USER, curses.COLOR_BLUE, -1),
        (PAIR_ASSISTANT, curses.COLOR_MAGENTA, -1),
        (PAIR_SYSTEM, curses.COLOR_CYAN, -1),
        (PAIR_TOOL_OK, curses.COLOR_GREEN, -1),
        (PAIR_TOOL_ERR, curses.COLOR_RED, -1),
        (PAIR_TOOL_WAIT, curses.COLOR_YELLOW, -1),
        (PAIR_DIFF_ADD, curses.COLOR_GREEN, -1),
        (PAIR_DIFF_DEL, curses.COLOR_RED, -1),
        (PAIR_DIFF_HUNK, curses.COLOR_CYAN, -1),
        (PAIR_DIVIDER, curses.COLOR_CYAN, -1),
        (PAIR_HELP_BAR, curses.COLOR_BLACK, curses.COLOR_CYAN),
        (PAIR_TOP_BAR, curses.COLOR_BLACK, curses.COLOR_WHITE),
        (PAIR_DIM, curses.COLOR_WHITE, -1),
        (PAIR_HIGHLIGHT, curses.COLOR_BLACK, curses.COLOR_YELLOW),
    ]
    for idx, fg, bg in pairs:
        try:
            curses.init_pair(idx, fg, bg)
        except curses.error:
            pass


def _classify_line(line: str) -> int:
    if not line:
        return PAIR_DEFAULT
    if _RE_USER.match(line):
        return PAIR_USER
    if _RE_ASSISTANT.match(line):
        return PAIR_ASSISTANT
    if _RE_SYSTEM.match(line):
        return PAIR_SYSTEM
    if _RE_TOOL_OK.match(line):
        return PAIR_TOOL_OK
    if _RE_TOOL_ERR.match(line):
        return PAIR_TOOL_ERR
    if _RE_TOOL_WAIT.match(line):
        return PAIR_TOOL_WAIT
    if _RE_DIVIDER.match(line):
        return PAIR_DIVIDER
    if _RE_DIFF_HUNK.match(line):
        return PAIR_DIFF_HUNK
    if _RE_DIFF_ADD.match(line):
        return PAIR_DIFF_ADD
    if _RE_DIFF_DEL.match(line):
        return PAIR_DIFF_DEL
    if _RE_HEADER_LABEL.match(line) or _RE_INDENT_DIM.match(line):
        return PAIR_DIM
    return PAIR_DEFAULT


# ── Drawing ──────────────────────────────────────────────────────────────────


def _draw(stdscr: curses._CursesWindow, state: _State) -> None:
    stdscr.erase()
    h, w = stdscr.getmaxyx()
    body_h = max(1, h - 2)

    # Clamp scroll range.
    max_scroll = max(0, len(state.lines) - body_h)
    if state.scroll > max_scroll:
        state.scroll = max_scroll
    if state.scroll < 0:
        state.scroll = 0

    # Top bar.
    top = _format_top_bar(state, w)
    _safe_addstr(
        stdscr, 0, 0,
        top.ljust(w),
        curses.color_pair(PAIR_TOP_BAR) | curses.A_BOLD,
    )

    # Body lines.
    for screen_row in range(body_h):
        idx = state.scroll + screen_row
        if idx >= len(state.lines):
            break
        line = state.lines[idx]
        attr = curses.color_pair(state.pairs[idx])
        # Bold the role headers and section headers for emphasis.
        if state.pairs[idx] in (PAIR_USER, PAIR_ASSISTANT, PAIR_DIVIDER):
            attr |= curses.A_BOLD
        if state.pairs[idx] == PAIR_DIM:
            attr |= curses.A_DIM
        _safe_addstr(stdscr, 1 + screen_row, 0, line, attr)
        # Highlight search matches in this line.
        if state.search:
            _highlight_matches(stdscr, 1 + screen_row, line, state.search, w)

    # Bottom help bar.
    help_text = HELP_BAR
    if state.message:
        help_text = state.message
    pos = _position_indicator(state, body_h)
    bottom = _truncate_to_width(help_text, w - len(pos) - 1) + " " + pos
    _safe_addstr(
        stdscr, h - 1, 0,
        bottom.ljust(w),
        curses.color_pair(PAIR_HELP_BAR) | curses.A_BOLD,
    )

    stdscr.refresh()


def _format_top_bar(state: _State, w: int) -> str:
    meta = state.ns.meta
    bits = []
    if meta.summary:
        bits.append(meta.summary)
    elif meta.session_id:
        bits.append(meta.session_id[:12])
    if meta.is_active:
        bits.append("● ACTIVE")
    if meta.current_model:
        bits.append(meta.current_model)
    branch = meta.branch or ""
    if branch:
        bits.append(branch)
    bar = "  " + " · ".join(bits)
    extras = []
    extras.append(f"tools:{state.tools_mode}")
    if not state.show_system:
        extras.append("sys:hidden")
    extras_text = "  [" + " | ".join(extras) + "]"
    if len(bar) + len(extras_text) + 2 < w:
        bar = bar + " " * (w - len(bar) - len(extras_text)) + extras_text
    return _truncate_to_width(bar, w)


def _position_indicator(state: _State, body_h: int) -> str:
    total = max(1, len(state.lines))
    end = min(total, state.scroll + body_h)
    pct = int(100 * end / total) if total else 100
    return f"{end}/{total}  {pct}%"


def _highlight_matches(
    stdscr: curses._CursesWindow,
    row: int,
    line: str,
    needle: str,
    w: int,
) -> None:
    if not needle:
        return
    n = needle.lower()
    haystack = line.lower()
    start = 0
    attr = curses.color_pair(PAIR_HIGHLIGHT) | curses.A_BOLD
    while True:
        i = haystack.find(n, start)
        if i < 0 or i >= w:
            break
        chunk = line[i : i + len(needle)]
        _safe_addstr(stdscr, row, i, chunk, attr)
        start = i + max(1, len(needle))


# ── Key handling ─────────────────────────────────────────────────────────────


def _handle_key(state: _State, stdscr: curses._CursesWindow, key) -> str | None:
    h, w = stdscr.getmaxyx()
    body_h = max(1, h - 2)
    state.message = ""

    # Translate single-char keys (get_wch returns int for special keys, str for chars)
    if isinstance(key, str):
        ch = key
        code = -1
    else:
        ch = ""
        code = int(key)

    if ch in ("q", "Q") or code == 27:  # Esc
        return "quit"
    if ch == "j" or code == curses.KEY_DOWN:
        state.scroll += 1
        return None
    if ch == "k" or code == curses.KEY_UP:
        state.scroll = max(0, state.scroll - 1)
        return None
    if ch == " " or code == curses.KEY_NPAGE:
        state.scroll += body_h // 2
        return None
    if ch == "b" or code == curses.KEY_PPAGE:
        state.scroll = max(0, state.scroll - body_h // 2)
        return None
    if ch == "g":
        state.scroll = 0
        return None
    if ch == "G":
        state.scroll = max(0, len(state.lines) - body_h)
        return None
    if ch == "n":
        # Next turn header *below* the current scroll position.
        starts = state.turn_starts()
        for s in starts:
            if s > state.scroll:
                state.scroll = s
                state.message = f"Jumped to line {s + 1}"
                return None
        state.message = "(no more turns below)"
        return None
    if ch == "N":
        starts = state.turn_starts()
        for s in reversed(starts):
            if s < state.scroll:
                state.scroll = s
                state.message = f"Jumped to line {s + 1}"
                return None
        state.message = "(no more turns above)"
        return None
    if ch == "t":
        order = ["brief", "full", "none"]
        i = (order.index(state.tools_mode) + 1) % len(order)
        state.tools_mode = order[i]
        # Preserve roughly the same scroll position by anchoring on a line index.
        state.refresh_lines()
        state.message = f"tools = {state.tools_mode}"
        return None
    if ch == "s":
        state.show_system = not state.show_system
        state.refresh_lines()
        state.message = f"system events {'shown' if state.show_system else 'hidden'}"
        return None
    if ch == "/":
        q = _prompt(stdscr, "/")
        if q is None:
            return None
        state.search = q
        state.last_search_dir = 1
        _seek_match(state, body_h)
        return None
    if ch == "?":
        q = _prompt(stdscr, "?")
        if q is None:
            return None
        state.search = q
        state.last_search_dir = -1
        _seek_match(state, body_h)
        return None
    if code == curses.KEY_RESIZE:
        return None
    return None


def _seek_match(state: _State, body_h: int) -> None:
    if not state.search:
        return
    needle = state.search.lower()
    if state.last_search_dir > 0:
        for i in range(state.scroll + 1, len(state.lines)):
            if needle in state.lines[i].lower():
                state.scroll = i
                state.message = f"match: line {i + 1}"
                return
        state.message = f"no match below for '{state.search}'"
    else:
        for i in range(state.scroll - 1, -1, -1):
            if needle in state.lines[i].lower():
                state.scroll = i
                state.message = f"match: line {i + 1}"
                return
        state.message = f"no match above for '{state.search}'"


def _prompt(stdscr: curses._CursesWindow, sigil: str) -> str | None:
    """Take a single-line input at the bottom prompt. Esc cancels (returns None)."""
    h, w = stdscr.getmaxyx()
    buf = ""
    curses.curs_set(1)
    try:
        while True:
            _safe_addstr(
                stdscr, h - 1, 0,
                (sigil + buf).ljust(w),
                curses.color_pair(PAIR_HELP_BAR) | curses.A_BOLD,
            )
            stdscr.move(h - 1, min(w - 1, 1 + len(buf)))
            stdscr.refresh()
            key = stdscr.get_wch() if hasattr(stdscr, "get_wch") else stdscr.getch()
            if isinstance(key, str):
                if key == "\n" or key == "\r":
                    return buf
                if key == "\x1b":  # Esc
                    return None
                if key in ("\b", "\x7f"):  # backspace
                    buf = buf[:-1]
                    continue
                if key.isprintable():
                    buf += key
                    continue
            else:
                if key == 10 or key == 13:
                    return buf
                if key == 27:
                    return None
                if key in (curses.KEY_BACKSPACE, 127, 8):
                    buf = buf[:-1]
                    continue
    finally:
        curses.curs_set(0)


# ── Helpers ──────────────────────────────────────────────────────────────────


def _safe_addstr(
    stdscr: curses._CursesWindow,
    y: int,
    x: int,
    text: str,
    attr: int = 0,
) -> None:
    """addstr that won't blow up at the bottom-right cell or on bad encodings."""
    h, w = stdscr.getmaxyx()
    if y < 0 or y >= h or x < 0 or x >= w:
        return
    try:
        stdscr.addnstr(y, x, text, w - x, attr)
    except curses.error:
        pass


def _truncate_to_width(text: str, w: int) -> str:
    if w <= 0:
        return ""
    if len(text) <= w:
        return text
    if w <= 1:
        return text[:w]
    return text[: w - 1] + "…"
